#language: php
#
#sudo: false
#
#php:
#  - 5.5
#  - 5.6
#  - 7.0
#
#before_script:
#  - curl --version
#  - composer self-update
#  - composer install --no-interaction --prefer-source --dev
#  - ~/.nvm/nvm.sh install v0.6.14
#  - ~/.nvm/nvm.sh run v0.6.14
#
#script: make test
#
#matrix:
#  allow_failures:
#    - php: 7.0
#  fast_finish: true
#
#before_deploy:
#  - make package
#
#
