language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install

script:
  - echo $PATH
  - phpunit

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
